"$schema" = 'https://starship.rs/config-schema.json'

[hostname]
format = "[$hostname]($style):"

[username]
disabled = true

[git_branch]
format = "[$branch(:$remote_branch)]($style) "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[shell]
disabled = false

[custom.INCOGNITO]
when = "$env.INCOGNITO"
format = "[🥷]($style) "
